### ISSUE TITLE
Installation size

### ISSUE THREAD

**Issue by StenApp** [ianis58/tiny11builder#10]
What i expected was 8GB usage of Windows 11 folder…
I had 16.5GB
I got 12.5GB and i have the WinSXS folder.

I‘m confused, how much should it have.
I used Win 11 de 22H2, had to skip downloading iso, used mine as c:\windows11.iso

**Comment by ianis58** [comment]
By looking on the internet, we see that trying to remove stuff from winsxs will always lead to issues. So as it's the bigger folder in a windows installation, there is no safe way to have a stable windows installation and at the same time to drastically decrease the installation size.
If you want a light OS, you have to use something different like a light Linux. ZorinOS is nice, ElementaryOS too, but also a classic Debian with Gnome IMHO.

**Comment by StenApp** [comment]
I had some errors during tiny11.iso creation so i was wondering how small it should be on drive.
I know removing WinSXS would would kill windows

**Comment by ianis58** [comment]
The red errors are normal, I let them happen because I'm lazy but it's not a problem. There is a word about it on the readme of this repo.
Windows 11 is a very large system even after a fresh install and it keep growing with updates. Unfortunately we can't do much about it.
