### ISSUE TITLE
[Fatal] Download button was not found.

### ISSUE THREAD

**Issue by godrider** [ianis58/tiny11builder#13]
I am unable to use this script from my Windows 10 Home machine.  What gives?

```
PS D:\Downloads\tiny11builder-main> Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass                          
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PS D:\Downloads\tiny11builder-main> .\tiny11creator.ps1
Loading configuration from config.json...
Creating needed variables...
Downloading WindowsIsoDownloader release from GitHub...
Extracting WindowsIsoDownloader release...
Downloading Windows 11 iso file from Microsoft using WindowsIsoDownloader...
[Info] Installing dependencies for Playwright...
[Success] Playwright dependencies installed.
[Info] Trying to obtain Windows 11 iso download link...
[Fatal] Download button was not found.
Unable to build the tiny11 iso (an error occured while trying to download the original iso using WindowsIsoDownloader).
Removing work folders...
PS D:\Downloads\tiny11builder-main>
```

**Comment by ianis58** [comment]
Hello,
I tried it today and it seems to be able to find the download link.
Can you ensure you have the latest version of the repo downloaded to your computer and try again?
Let me know!

**Comment by godrider** [comment]
I redownloaded it, ran it, but got the same error. I tried downloading Windows 11 from the official Microsoft website and it got me this error. It looks like I'm just unlucky.

> Error
> We are unable to complete your request at this time. Some users, entities and locations are banned from using this service. For this reason, leveraging anonymous or location hiding technologies when connecting to this service is not generally allowed. If you believe that you encountered this problem in error, please try again. If the problem persists you may contact [Microsoft Support – Contact Us ](https://support.microsoft.com/en-gb/contactus/)page for assistance. Refer to message code 715-123130 and 0f55f220-624b-4a93-9b06-d8d4ea8f54b9.

**Comment by xZetsubou** [comment]
Are sure that you are not using a VPN or sus DNS ? it seems ur IP is blocked from MS.

**Comment by godrider** [comment]
> Are sure that you are not using a VPN or sus DNS ? it seems ur IP is blocked from MS.

Oh shit, you're right, haha. I totally forgot I was running a DNS sinkhole. Apparently it was blocking some MS requests. Now it's downloading the ISO file.
