### ISSUE TITLE
Error code: 0x8030002F

### ISSUE THREAD

**Issue by morpho0** [ianis58/tiny11builder#5]
The script successfully created tiny11.iso which was able to mount. However, once mounted setup.exe displays a window called 'Install Windows' which reads off 'Error code: 0x8030002F'.

Assuming that I have followed all the instructions for this script correctly, what could be causing the error code?

**Comment by ianis58** [comment]
Hello @morpho0 
It's a nice test, I didn't think of using the image as-is to try an upgrade. Are you trying to upgrade win10 to win11?
I use the ISO image to create a bootable USB stick (to do so you can use "balena etcher", or "rufus").

**Comment by ianis58** [comment]
No answer, closing.
