### ISSUE TITLE
error running - Remove-WindowsPackage : The specified package is not valid Windows package

### ISSUE THREAD

**Issue by uebermann1** [ianis58/tiny11builder#7]
Just downloaded and tried to run from my D drive using Power Shell (Admin) , however this error comes up when trying to remove some of the packages from the ISO.  Here's the copy/paste:

[Success] ISO Downloaded successfully! Exiting with code 0.                                                             Mounting the original iso...                                                                                            Creating temporary folders...                                                                                           Copying the content of the original iso to the work folder...                                                           Unmounting the original iso...                                                                                          Mounting the install.wim image...                                                                                       Removing unwanted app packages from the install.wim image...                                                            Removing unwanted windows packages from the install.wim image...                                                        Remove-WindowsPackage : The specified package is not valid Windows package.
At D:\download\tiny11builder-main\tiny11creator.ps1:85 char:5
+ ...             Remove-WindowsPackage -Path $installImageFolder -PackageN ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-WindowsPackage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.RemoveWindowsPackageCommand

Remove-WindowsPackage : The specified package is not valid Windows package.
At D:\download\tiny11builder-main\tiny11creator.ps1:85 char:5
+ ...             Remove-WindowsPackage -Path $installImageFolder -PackageN ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-WindowsPackage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.RemoveWindowsPackageCommand

Remove-WindowsPackage : The specified package is not valid Windows package.
At D:\download\tiny11builder-main\tiny11creator.ps1:85 char:5
+ ...             Remove-WindowsPackage -Path $installImageFolder -PackageN ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-WindowsPackage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.RemoveWindowsPackageCommand

Remove-WindowsPackage : The specified package is not valid Windows package.
At D:\download\tiny11builder-main\tiny11creator.ps1:85 char:5
+ ...             Remove-WindowsPackage -Path $installImageFolder -PackageN ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-WindowsPackage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.RemoveWindowsPackageCommand

Deleting PathsToDelete from the install.wim image...
c:\tiny11\installimage\Program Files\WindowsApps\MicrosoftWindows.Client.WebExperience_421.20070.195.0_x64__cw5n1h2txyewy\Dashboard\WebContent\node_modules\@babel\plugin-transform-modules-commonjs\node_modules\@babel\helper-member-expression-to-functions\lib\*: The system cannot find the path specified.
c:\tiny11\installimage\Windows\System32\LogFiles\WMI\RtBackup\*: Access is denied.
c:\tiny11\installimage\Windows\System32\WebThreatDefSvc\*: Access is denied.
Patching the registry in the install.wim image...
Placing the autounattend.xml file in the install.wim image...
Unmounting the install.wim image...
Creating a clean install.wim image without all unnecessary indexes...
Mounting the boot.wim image...
Patching the registry in the boot.wim image...
Unmounting the boot.wim image...
Creating a clean boot.wim image without all unnecessary indexes...
Building the tiny11.iso file...
100% completece tree (500 files in 43 directories) 0% complete
Removing work folders...

I assume this is due to changes MS made to the ISO but wanting to confirm.  Thank you.

**Comment by ianis58** [comment]
Please look at the readme (home of the respository), that error is mentioned in the step 3 of the "Run it" section.
So I think you correctly built the tiny11 iso. If you install it and have issues, please update here !
