### ISSUE TITLE
Created iso is unusable

### ISSUE THREAD

**Issue by FPSUsername** [ianis58/tiny11builder#9]
![image](https://github.com/ianis58/tiny11builder/assets/10143926/92a0dc6c-2ea0-4945-be85-c6ec1544cc28)

**Comment by ianis58** [comment]
Where is that error showing?
Please explain the steps you took to get that error

**Comment by FPSUsername** [comment]
I ran the tool with admin rights and put a "windows11.iso" file in C:\.
The windows iso is downloaded from the Microsoft website, it's not created using the media creation tool (the downloaded iso is about 1GB larger).

**Comment by ianis58** [comment]
Not relevant anymore, closing.
